spring:

  application:
    name: conference-system

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true

  modulith:
    republish-outstanding-events-on-restart: true
    events.jdbc.schema-initialization.enabled: true

logging:
  level:
    org.springframework: debug

server:
  error:
    include-message: always

