spring:

  application:
    name: conference-system

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema/*sql
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

logging:
  level:
    org:
      springframework:
        security: INFO