spring:

  application:
    name: conference-system

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        security: debug
        
server:
  error:
    include-message: always
