GET http://localhost:8080/tickets
Accept: application/json

###

POST http://localhost:8080/tickets/buy
Accept: application/json
Content-Type: application/json

{
  "category": "REGULAR",
  "date": "2024-04-24",
  "price": 150,
  "status": "PENDING"
}